### ISSUE TITLE
Hint about Git Ignores

### ISSUE THREAD

**Issue by bcarpenter** [thumblemonks/smurf#1]
This isn't a bug, but it bit me (and I initially thought it was a bug w/Smurf).

I was getting weird errors on my production machine because the all.css file wasn't getting updated.  I happened to have accidentally checked these two cache files generated by Smurf into git.

Maybe add a note about making entries in myapp/.gitignore for the all.js and all.css files that smurf generates.

**Comment by thumblemonks** [comment]
Dear Mr. bcarpenter,

Thanks! Not a bad point at all.

**Comment by thumblemonks** [comment]
Ok. I mentioned it in the Readme. Open this issue back if you don't like. Thanks again.
