### ISSUE TITLE
Can you please build a new version not requiring Rails 3.0.3?

### ISSUE THREAD

**Issue by rynr** [thumblemonks/smurf#15]
Rails 3.0.4 is out and it's not possible to update with the current smurf-version.

**Comment by peppyheppy** [comment]
Hi rjung,

You bring up a good point. Feel free to send over a patch with tests and I would be more than happy to accept it and push out a new version of the gem.

Thanks for using Smurf!

Paul

**Comment by rynr** [comment]
Well, f1997ec5e68462f955bf84db7420afad6ec26f6f already does fix the problem. You just need to build a new Gem-Version.

**Comment by peppyheppy** [comment]
The current gem is version 1.0.5. https://rubygems.org/gems/smurf/versions/1.0.5

Are you using the latest version that includes the commit you were referring to?

Paul

**Comment by rynr** [comment]
No, it's not fixed with 1.0.5.
Take a look at the Dependencies at https://rubygems.org/gems/smurf/versions/1.0.5 . It says:

> Runtime Dependencies
> 
> rails = 3.0.3

These are Runtime Dependencies. With the commit f1997ec5e68462f955bf84db7420afad6ec26f6f the Dependency is moved to the Development Dependencies within the Gemfile and is removed from the gemspec.

You just need to release a new Gem-Version with the current Gemfile.

By the way, Issue 16 is the same topic.

**Comment by peppyheppy** [comment]
Sorry for the confusion on this. It looks like the version was bumped but the change wasn't included. I just bumped the patch version after ensuring that all of the runtime dependencies were fixed. Please let me know if there is anything else. Thanks for your persistence on this. 

Paul

**Comment by rynr** [comment]
Yeah, Thanks!
