### ISSUE TITLE
Rails =3.0.3 dependency 

### ISSUE THREAD

**Issue by tscolari** [thumblemonks/smurf#16]
This restriction is preventing bundler from updating to rails 3.0.4

**Comment by peppyheppy** [comment]
Hi tscolar,

Thanks for using smurf.

What version of smurf are you running. This runtime dependency was fixed in version 1.0.5. Please make sure that your Gemfile has the latest version configured.

Paul

**Comment by rynr** [comment]
This is the same Topic as Issue 15.

**Comment by peppyheppy** [comment]
Sorry for the confusion on this. It looks like the version was bumped but the change wasn't included. I just bumped the patch version after ensuring that all of the runtime dependencies were fixed. Please let me know if there is anything else. Thanks for your persistence on this. 

Please update your Gemfile with version 1.0.6, thanks!

Paul

**Comment by tscolari** [comment]
thank you! :)
