### ISSUE TITLE
Doesn't load it in public/stylesheet/cache and public/javascript/cache

### ISSUE THREAD

**Issue by brodock** [thumblemonks/smurf#3]
Is it correct? As the instructions tell us about public/_/cache/_ to go to gitignore.

**Comment by thumblemonks** [comment]
Hey Gabriel,

Usually the directories will be named /public/javascripts and public/stylesheets (note the plurality). I'm not sure if this is important for your example or not.

Can you provide some more info about what the actual problem is?

Cheers,
gus
