### ISSUE TITLE
Nothing's actually happening for me

### ISSUE THREAD

**Issue by ghost** [thumblemonks/smurf#5]
Rails 2.3.5 app deployed with Passenger and their "enterprise" Ruby build. Installed smurf gem and turned caching on for development environment. Cache files are generated in public/javascripts and public/stylesheets normally, but they are never actually minimized. Deleting all cache files and restarting the app has no effect.  

Gem is definitely in the right place, as a config.gem dependency succeeds. Where should I start digging to find the problem?

**Comment by ghost** [comment]
Solved it myself: 

:smurf needs to be listed in config.plugins if it's not set to :all.

**Comment by thumblemonks** [comment]
Hey there,

I meant to get back to you earlier, but I am glad you had some resolution. It seems strange that you would have to list Smurf as a plugin if you are using the gem version. I only ever do one or the other.

If you ever get some free time to play with it, could you try deleting Smurf from vendor/plugins, removing all Smurf gems, installing as a gem and see what happens (make sure to remove :smurf from the `config.plugins` declaration)?
