### ISSUE TITLE
Stripping needed conditional comments for IE only

### ISSUE THREAD

**Issue by chrissloan** [thumblemonks/smurf#9]
Noticed that Smurf, while great, strips the /*@cc_on IE only conditionals needed when pinpointing IE only javascript. Can Smurf be updated to ignore these type of conditional comments. This happens when using and combining the HTML5shiv js code from:

http://code.google.com/p/html5shiv/

**Comment by gus** [comment]
How crazy. I just received a pull request from user peppyheppy with some fixes for html5shiv. I'll take a look and hopefully the fixes will address your issue as well.

If they don't, we'll have to take a look at jsmin library ported from Crockford's version.

**Comment by chrissloan** [comment]
Yes, he is a coworker of mine who forked the the project and implemented the fix into a project we are working on. His fix works perfectly so hopefully it will work in the main base for Smurf.

**Comment by gus** [comment]
Awesome! I already applied and released a brand new version. Available now.

Thanks to you both.
